In [1]:
# Import TensorFlow
import tensorflow as tf

# Import numpy
import numpy as np


try:
    %tensorflow_version 2.2 #colab only
except Exception:
    pass

# Check the Tensorflow version
print('Tensorflow version: %s' % tf.__version__)


Tensorflow version: 2.4.1


In [4]:
# Check the GPU device availability
print('Num GPUs Available: %d' %len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available: 1


In [5]:
# Create a tensor as a vector (one dimension)
vector_a = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0, 6.0])
print(vector_a)

tf.Tensor([1. 2. 3. 4. 5. 6.], shape=(6,), dtype=float32)


In [6]:
# Create a tensor as a matrix (two dimensions) layout: 3x2
matrix_b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])
print(matrix_b)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32)


In [7]:
# Create two matrices
m_a = tf.constant([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
m_b = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

# Matrix multiply (m_b * m_a)
m_ba = tf.matmul(m_b, m_a)
print(m_ba)

tf.Tensor(
[[ 9. 12. 15.]
 [19. 26. 33.]
 [29. 40. 51.]], shape=(3, 3), dtype=float32)


In [11]:
# Matrix multiply (m_a * m_b) different from the previous ones
m_ab = tf.matmul(m_a, m_b)
print(m_ab)

# Convert to numpy
m_ab.numpy()

tf.Tensor(
[[22. 28.]
 [49. 64.]], shape=(2, 2), dtype=float32)


array([[22., 28.],
       [49., 64.]], dtype=float32)

In [10]:
# Define the feature and the label
model_data = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0], dtype=float)
model_value = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0, 9.0, 11.0], dtype=float)